/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsImport } from './routes/products'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as ProductCustomGuitarImport } from './routes/product/custom-guitar'
import { Route as ProductSlugImport } from './routes/product/$slug'

// Create/Update Routes

const ProductsRoute = ProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductCustomGuitarRoute = ProductCustomGuitarImport.update({
  id: '/product/custom-guitar',
  path: '/product/custom-guitar',
  getParentRoute: () => rootRoute,
} as any)

const ProductSlugRoute = ProductSlugImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsImport
      parentRoute: typeof rootRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugImport
      parentRoute: typeof rootRoute
    }
    '/product/custom-guitar': {
      id: '/product/custom-guitar'
      path: '/product/custom-guitar'
      fullPath: '/product/custom-guitar'
      preLoaderRoute: typeof ProductCustomGuitarImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/products': typeof ProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/custom-guitar': typeof ProductCustomGuitarRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/products': typeof ProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/custom-guitar': typeof ProductCustomGuitarRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/products': typeof ProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/custom-guitar': typeof ProductCustomGuitarRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/products'
    | '/product/$slug'
    | '/product/custom-guitar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/products' | '/product/$slug' | '/product/custom-guitar'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/products'
    | '/product/$slug'
    | '/product/custom-guitar'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ProductsRoute: typeof ProductsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductCustomGuitarRoute: typeof ProductCustomGuitarRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ProductsRoute: ProductsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductCustomGuitarRoute: ProductCustomGuitarRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cart",
        "/products",
        "/product/$slug",
        "/product/custom-guitar"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/products": {
      "filePath": "products.tsx"
    },
    "/product/$slug": {
      "filePath": "product/$slug.tsx"
    },
    "/product/custom-guitar": {
      "filePath": "product/custom-guitar.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
